restaurant.name=Bar Mleczny
restaurant.capacity=50
restaurant.description=Name=${restaurant.name}, Capacity=${restaurant.capacity}, Owner=${restaurant.owner:Andrew}


restaurant.menu.itemsString=Spaghetti Bolognese,Caesar Salad,Grilled Salmon